<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [1]:
import pandas as pd

Load the dataset into a dataframe.

In [2]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [3]:
# your code goes here
df.duplicated().value_counts()
#---> There are 154 duplicate Rows

False    11398
True       154
dtype: int64

In [5]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11547,25136,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,36.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Difficult
11548,25137,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Poland,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Tech...,25.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
11549,25138,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,34.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
11550,25141,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Switzerland,No,"Secondary school (e.g. American high school, G...",NaN,...,Somewhat less welcome now than last year,NaN,25.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
11551,25142,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United Kingdom,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A natural science (ex. biology, chemistry, phy...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,30.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Easy

In [9]:
# number of Duplicates in the Respondent Column:
df["Respondent"].duplicated().value_counts()

False    11398
True       154
Name: Respondent, dtype: int64

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [10]:
# your code goes here
df.drop_duplicates(keep="first", inplace=True)

Verify if duplicates were actually dropped.

In [11]:
# your code goes here
# checking again for duplicates
df.duplicated().value_counts()      #--> no duplicate rows left in Dataset

False    11398
dtype: int64

In [12]:
df["Respondent"].nunique()

11398

## Finding Missing values

In [13]:
len(df)

11398

Find the missing values for all columns.

In [14]:
# Loop, that prints the number of Missing Values for all columns:
for i in df.columns:
    #print(df[i].isna().value_counts())
    if df[i].isna().value_counts()[0]== 11398:
        print(f"Column {i} has no missing values.")
    elif df[i].isna().value_counts()[0] != 11398:
        print(f"Column {i} has {df[i].isna().value_counts()[1]} missing values.")

Column Respondent has no missing values.
Column MainBranch has no missing values.
Column Hobbyist has no missing values.
Column OpenSourcer has no missing values.
Column OpenSource has 81 missing values.
Column Employment has no missing values.
Column Country has no missing values.
Column Student has 51 missing values.
Column EdLevel has 112 missing values.
Column UndergradMajor has 737 missing values.
Column EduOther has 164 missing values.
Column OrgSize has 96 missing values.
Column DevType has 65 missing values.
Column YearsCode has 9 missing values.
Column Age1stCode has 13 missing values.
Column YearsCodePro has 16 missing values.
Column CareerSat has no missing values.
Column JobSat has 1 missing values.
Column MgrIdiot has 493 missing values.
Column MgrMoney has 497 missing values.
Column MgrWant has 493 missing values.
Column JobSeek has no missing values.
Column LastHireDate has no missing values.
Column LastInt has 413 missing values.
Column FizzBuzz has 37 missing values.
Column JobFactors has 3 missing values.
Column ResumeUpdate has 39 missing values.
Column CurrencySymbol has no missing values.
Column CurrencyDesc has no missing values.
Column CompTotal has 809 missing values.
Column CompFreq has 206 missing values.
Column ConvertedComp has 816 missing values.
Column WorkWeekHrs has 122 missing values.
Column WorkPlan has 121 missing values.
Column WorkChallenge has 164 missing values.
Column WorkRemote has 8 missing values.
Column WorkLoc has 32 missing values.
Column ImpSyn has 5 missing values.
Column CodeRev has 1 missing values.
Column CodeRevHrs has 2426 missing values.
Column UnitTests has 29 missing values.
Column PurchaseHow has 196 missing values.
Column PurchaseWhat has 38 missing values.
Column LanguageWorkedWith has 11 missing values.
Column LanguageDesireNextYear has 134 missing values.
Column DatabaseWorkedWith has 453 missing values.
Column DatabaseDesireNextYear has 1042 missing values.
Column PlatformWorkedWith has 411 missing values.
Column PlatformDesireNextYear has 544 missing values.
Column WebFrameWorkedWith has 1393 missing values.
Column WebFrameDesireNextYear has 1617 missing values.
Column MiscTechWorkedWith has 2182 missing values.
Column MiscTechDesireNextYear has 1455 missing values.
Column DevEnviron has 29 missing values.
Column OpSys has 34 missing values.
Column Containers has 82 missing values.
Column BlockchainOrg has 2322 missing values.
Column BlockchainIs has 2610 missing values.
Column BetterLife has 98 missing values.
Column ITperson has 35 missing values.
Column OffOn has 38 missing values.
Column SocialMedia has 293 missing values.
Column Extraversion has 20 missing values.
Column ScreenName has 507 missing values.
Column SOVisit1st has 325 missing values.
Column SOVisitFreq has 5 missing values.
Column SOVisitTo has 1 missing values.
Column SOFindAnswer has 3 missing values.
Column SOTimeSaved has 50 missing values.
Column SOHowMuchTime has 1917 missing values.
Column SOAccount has 1 missing values.
Column SOPartFreq has 1128 missing values.
Column SOJobs has 6 missing values.
Column EntTeams has 5 missing values.
Column SOComm has no missing values.
Column WelcomeChange has 85 missing values.
Column SONewContent has 1965 missing values.
Column Age has 287 missing values.
Column Gender has 73 missing values.
Column Trans has 123 missing values.
Column Sexuality has 542 missing values.
Column Ethnicity has 675 missing values.
Column Dependents has 140 missing values.
Column SurveyLength has 19 missing values.
Column SurveyEase has 14 missing values.

In [15]:
# Usind pd.isna() or pd.isnull()
# creating a function, that gives out the number of missing Values od each Column of a DataFrame:
def mising_values_column(df, column):
        """ Input: DataFrame and column name as a string
            Outpur: Print Statement with column name and the corresponding number of missing values"""
        if df[column].isna().value_counts()[0]== len(df):
            return(f"Column: {column} Number of missing values: 0")
        elif df[column].isna().value_counts()[0] != len(df):
            return(f"Column: {column}, Number of missing values: {df[column].isna().value_counts()[1]}")

In [17]:
# Calling the Function:
mising_values_column(df,"Country")

'Column: Country Number of missing values: 0'

Find out how many rows are missing in the column 'WorkLoc'

In [18]:
# your code goes here
# Calling the Function:
mising_values_column(df,"WorkLoc")  #--> 32 missing Values

'Column: WorkLoc, Number of missing values: 32'

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [19]:
# your code goes here
df["WorkLoc"].value_counts()

Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64

What is the majority category under the column Employment?

In [20]:
df["Employment"].value_counts()

Employed full-time    10968
Employed part-time      430
Name: Employment, dtype: int64

Under the column " UndergradMajor", which category has the minimum number of rows?

In [21]:
df["UndergradMajor"].value_counts()

Computer science, computer engineering, or software engineering          6953
Information systems, information technology, or system administration     794
Another engineering discipline (ex. civil, electrical, mechanical)        759
Web development or web design                                             410
A natural science (ex. biology, chemistry, physics)                       403
Mathematics or statistics                                                 372
A business discipline (ex. accounting, finance, marketing)                244
A social science (ex. anthropology, psychology, political science)        210
A humanities discipline (ex. literature, history, philosophy)             207
Fine arts or performing arts (ex. graphic design, music, studio art)      161
I never declared a major                                                  124
A health science (ex. nursing, pharmacy, radiology)                        24
Name: UndergradMajor, dtype: int64

The column ‘ConvertedComp’ contains the annual compensation of the survey respondents. What is the best approach to impute the missing values in this column?

In [22]:
df["ConvertedComp"].value_counts()

2000000.0    138
1000000.0    105
100000.0      99
150000.0      92
120000.0      86
            ...
79183.0        1
20475.0        1
288732.0       1
22056.0        1
19880.0        1
Name: ConvertedComp, Length: 3515, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [24]:
#make a note of the majority value here, for future reference
# most frequent WorkLoc is Office: 6806

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [27]:
# your code goes here
df["WorkLoc"].fillna("Office",inplace=True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [29]:
# your code goes here
df["WorkLoc"].value_counts()
# no missing Values left in the WorkLoc column:

Office                                            6838
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq". 

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [30]:
# your code goes here
df["CompFreq"].value_counts()

Yearly     6073
Monthly    4788
Weekly      331
Name: CompFreq, dtype: int64

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [31]:
# your code goes here
# creating dictionairy for the Mapinf process:
categories = {"Yearly":1, "Monthly":12, "Weekly":52}
df["NormalizedAnnualCompensation"] = df["CompFreq"].map(categories) * df["CompTotal"]
df["NormalizedAnnualCompensation"]

0         61000.0
1        138000.0
2         90000.0
3        348000.0
4         90000.0
           ...
11547    130000.0
11548     74400.0
11549    105000.0
11550     80000.0
11551         NaN
Name: NormalizedAnnualCompensation, Length: 11398, dtype: float64

In [32]:
# lets Take a Look:
df[["CompFreq","CompTotal" ,"NormalizedAnnualCompensation"]]

      CompFreq  CompTotal  NormalizedAnnualCompensation
0       Yearly    61000.0                       61000.0
1       Yearly   138000.0                      138000.0
2       Yearly    90000.0                       90000.0
3      Monthly    29000.0                      348000.0
4       Yearly    90000.0                       90000.0
...        ...        ...                           ...
11547   Yearly   130000.0                      130000.0
11548   Yearly    74400.0                       74400.0
11549   Yearly   105000.0                      105000.0
11550   Yearly    80000.0                       80000.0
11551      NaN        NaN                           NaN

[11398 rows x 3 columns]

What is the median NormalizedAnnualCompensation?

In [33]:
df["NormalizedAnnualCompensation"].median()

100000.0

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).